<?php
/**
 * list view script
 *
 * This view script is the list page for all events
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php if ($this->auth()->hasIdentity()) :?>
<?php echo $this->actionList(array(
    $this->htmlAnchor('Create Event', array(
        'controller'=> 'events',
        'action'    => 'create',
    ))
));
?>
<?php endif; ?>

<?php foreach ($this->items as $event) : ?>

    <?php echo $this->eventItem($event); ?>

<?php endforeach; ?>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>