<?php
/**
 * list view script
 *
 * This view script is the list page for all events
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
    echo $this->model(new App_Model_Event)->create($this->user, 'Create Event');
?>

<?php
// iterate through the event rows
foreach ($this->items as $event) :
    echo $this->event($event)->item($this->user);
endforeach;

// render a pagination control
echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');

?>