<?php
/**
 * list view script
 *
 * This view script is the list page for all events
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php echo $this->actionList(array(
    $this->htmlAnchor('Create Event', array(
        'action'    => 'create',
    ))
));
?>

<?php foreach ($this->items as $event) : ?>

    <?php echo $this->eventItem($event); ?>

<?php endforeach; ?>