<?php
/**
 * view view script
 *
 * This view script is for viewing a single event record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<h2><?php echo $this->model->getValue('name'); ?></h2>

<?php if ($this->auth()->hasIdentity()) : ?>
<?php echo $this->actionList(array(
    $this->htmlAnchor('Edit', array(
        'controller' => 'events',
        'action'    => 'edit',
        'event_id'  => $this->model->id,
    )),
    $this->htmlAnchor('Delete', array(
        'controller'    => 'events',
        'action'        => 'delete',
        'event_id'      => $this->model->id,
    )),
)); ?>

<?php endif; ?>

<p><?php echo $this->model->getValue('description'); ?></p>

<h3>Leaderboards</h3>
<?php echo $this->action('view', 'leaderboards', 'default', array_merge(
    $this->request()->getParams(),
    array(
        'event_id'  => $this->model->id,
    )
)); ?>

<div class="two-column">
<h3>Competitions</h3>
<?php echo $this->action('list', 'competitions', 'default', array(
    'event_id'  => $this->model->id,
)); ?>

</div>

<div class="two-column">
<h3>Scales</h3>
<?php echo $this->action('list', 'scales', 'default', array(
    'event_id'  => $this->model->id,
)); ?>
</div>

<div class="clear-all">
<h3>Athletes</h3>
<?php echo $this->action('list', 'athletes', 'default', array(
    'event_id'  => $this->model->id,
)); ?>
</div>

