<?php
/**
 * view view script
 *
 * This view script is for viewing a single event record
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<div class="row">
    <h1 class="lead"><?php echo $this->model->getValue('name'); ?>
        <?php echo $this->event($this->model->row)->register($this->user); ?>
    </h1>

    <p class="row"><?php echo $this->model->getValue('description'); ?>
    <?php
        // echo editing links if the user has access to them
        echo $this->model($this->model)->links($this->user, array(
            'event_id' => $this->model->id,
        ));
    ?>
    </p>
</div>

<?php
    // store request params for use later
    $params = $this->request()->getParams();
?>

<div class="row">
    <div class="twelve columns">
        <section class="tabs">
            <?php

            // var_dump($this->navigation()->getAcl()); die;

                echo $this->navigation()
                    ->menu()
                    ->setMinDepth(1)
                    ->setUlClass('tab-nav')
                    ->render();

                $pages  = $this->navigation()->getContainer()->findOneBy('Label', 'Events');
                $acl    = $this->registry()->get('acl');
                $user   = $this->registry()->get('user');
                $role   = $user->getRoleId();

            ?>

            <?php foreach ($pages as $page) : ?>

            <div class="tab-content">

            <?php if ($acl->isAllowed($role, $page->controller, $page->action)) : ?>
                <h2><?php echo $page->getLabel(); ?></h2>

                <?php echo $this->action(
                    $page->action, $page->controller, $page->module, array_merge($params, array(
                        'event_id'  => $this->model->id,
                    ))
                ); ?>
            <?php endif; ?>

            </div>

            <?php endforeach; ?>

        </section>
    </div>
</div>
