<?php
/**
 * add scale view script
 *
 * This view script displays a form for adding a scale to an event
 *
 * @category    RxComps
 * @package     package
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php echo $this->form; ?>