<?php
/**
 * edit view script
 *
 * This view script displays a form for editing event information
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php echo $this->htmlList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
), false, array(
    'class' => 'subnav',
), false); ?>
<?php echo $this->form; ?>