<?php
/**
 * list view script
 *
 * This view script is the list page for all events
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
$eventId = $this->request()->getParam('event_id');

// echo a create new link, if appropriate
echo $this->model(new App_Model_Scale)->create($this->user, 'Add Scale', array(
    'event_id'  => $eventId,
));

// iterate through the registrations, outputing what's appropriate
foreach ($this->items as $scale) :
    echo $this->scale($scale)->item($this->user, array(
        'event_id'  => $eventId,
    ));

endforeach;

// render any necessary pagination controls
echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');

?>
