<?php
/**
 * view view script
 *
 * This view script is for viewing a single event record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php if ($this->auth()->hasIdentity()) :?>
<?php echo $this->actionList(array(
    $this->htmlAnchor('Create Scale', array(
        'action'    => 'create',
    )),
)); ?>
<?php endif; ?>

<h2><?php echo $this->model->getValue('name'); ?></h2>

<p><?php echo $this->model->getValue('description'); ?></p>
