<?php
/**
 * view view script
 *
 * This view script is for viewing a single event record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
$eventId = $this->request()->getParam('event_id');

// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
    $this->model(new App_Model_Scale)->create($this->user, 'Add Scale', array(
        'event_id'  => $eventId,
    )),
));

echo $this->scale($this->model)->item($this->user, array(
    'event_id'  => $eventId,
));

?>
