<?php
/**
 * Create view script
 *
 * This view script displays a form for creating
 *
 * @category    RxCompetition
 * @package     package
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php

// render a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
));
?>

<h1>Register for <?php echo $this->event()->getValue('name'); ?></h2>

<?php

// render the creation form
echo $this->form;

?>