<?php
/**
 * list view script
 *
 * This view script is the list page for all registrations
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2013 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<?php
$eventId = $this->request()->getParam('event_id');

// echo a create new link, if appropriate
echo $this->model(new App_Model_Registration)->create($this->user, 'Create Registration', array(
    'event_id'  => $eventId,
));

// echo a create new link, if appropriate
echo $this->model(new App_Model_Registration)->csv($this->user, 'Export Registrations', array(
    'event_id'  => $eventId,
));

// iterate through the registrations, outputing what's appropriate
foreach ($this->items as $registration) :

    echo $this->registration($registration)->item($this->user, array(
        'event_id' => $eventId,
    ));

endforeach;

// render any necessary pagination controls
echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');

?>