<?php
/**
 * view view script
 *
 * This view script is for viewing a single registration record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
$eventId = $this->request()->getParam('event_id');

// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
    $this->model(new App_Model_Score)->create($this->user, 'Add Score', array(
        'event_id'  => $eventId,
    )),
));
?>

<h1>Registration Details</h1>

<?php
$user = $this->model->getParent('User');
$athlete = $this->model->getParent('Athlete');
$event = $this->model->getParent('Event');

$user->row->gender = $athlete->row->gender;

echo $this->user($user->row)->profile($this->user, array(
    'event_id'  => $eventId,
));

echo $this->registration($this->model->row)->item($this->user, array(
    'event_id'  => $eventId,
));

echo $this->athlete($athlete->row)->item($this->user, array(
    'event_id'  => $eventId,
));

echo $this->event($event->row)->item($this->user, array(
    'event_id'  => $eventId,
))

?>