<?php
/**
 * list view script
 *
 * This view script is the list page for all competitions
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
// echo the appropriate link to create a new athlete
echo $this->model(new App_Model_Event)->create($this->user, 'Add Athlete', array(
    'event_id'  => $this->event()->id(),
));

// iterate through the athletes, rendering information
foreach ($this->items as $athlete) :

    echo $this->athleteItem($athlete, $this->user, array(
        'event_id'  => $this->event()->id(),
    ));

endforeach;

// output any pagination control necessary
echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');

?>