<?php

$headers = array(
    'Id', 'Fisrt Name', 'Last Name' 'Gym', 'scale', 'gender', 'sign-up-date',
);

echo '"' . implode('","', $headers) . '"' . PHP_EOL;

foreach ($this->items as $athlete) :

    $scale = $athlete->findParentRow('App_Model_DbTable_Scale');

    $name = explode(' ', $athlete->name);

    $data = array(
        $athlete->id,
        $name[0],
        $name[1],
        $athlete->gym,
        $scale->name,
        $athlete->gender,
        $athlete->created,
    );

    echo '"' . implode('","', $data) . '"' . PHP_EOL;

endforeach;
