<?php
/**
 * list view script
 *
 * This view script is the list page for all competitions
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
$eventId = $this->request()->getParam('event_id');

// echo the appropriate link to create a new athlete
echo $this->model(new App_Model_Athlete)->create($this->user, 'Add Athlete', array(
    'controller'    => 'athletes',
    'event_id'  => $eventId,
));

// echo a create new link, if appropriate
echo $this->model(new App_Model_Athlete)->csv($this->user, 'Export Athletes', array(
    'controller'    => 'athletes',
    'event_id'  => $eventId,
));

// echo a create new link, if appropriate
echo $this->model(new App_Model_Athlete)->search(array(
    'formAction' => array(
        'controller' => 'athletes',
        'action'    => 'search',
        'event_id'  => $eventId,
    ),
));

// iterate through the athletes, rendering information
foreach ($this->items as $athlete) :

    echo $this->athlete($athlete)->item($this->user, array(
        'event_id'  => $eventId,
    ));

endforeach;

// output any pagination control necessary
echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');

?>