<?php
/**
 * search view script
 *
 * This view script is for displaying search results
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>
<?php
// render a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink(new App_Model_Athlete, $this->request()->getParams()),
));

echo $this->form;
?>

<ul>
<?php foreach ($this->results as $result) : ?>
    <?php
    $doc = $result->getDocument();
    $link = $this->htmlAnchor($doc->name, array(
        'controller'=> 'athletes',
        'action'    => 'view',
        'id'        => $doc->id,
        'event_id'  => $doc->event_id,
    ));
    ?>
    <li>
        <h3><?php echo $link; ?>
            <span class="alt">(<?php echo $doc->gym; ?>)</span>
        </h3>
    </li>

<?php endforeach; ?>
</ul>