<?php
/**
 * view view script
 *
 * This view script is for viewing a single competition record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
    $this->model($this->model)->create($this->user, 'Add Score', array(
        'event_id'  => $this->event()->id(),
    )),
));


echo $this->athlete($this->model)->item($this->user, array(
    'event_id'  => $this->event()->id(),
));

?>

<h3>Scores</h3>

<?php
// render the score list for this athlete
echo $this->action('list', 'scores', 'default', array(
    'athlete_id' => $this->model->id,
));

?>
