<?php
/**
 * view view script
 *
 * This view script is for viewing a single event-option record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2013 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<?php
// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
    $this->model(new App_Model_EventOption)->create($this->user, 'Add Score', array(
        'event_id'  => $this->event()->id(),
    )),
));

echo $this->eventOption($this->model)->item($this->user, array(
    'event_id'  => $this->event()->id(),
));
?>
