<?php
/**
 * delete view script
 *
 * This view script displays a form for editing user information
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<h2>Delete User?</h2>

<p>
    Are you sure you want to delete this User [<?php echo $this->model->getValue('email'); ?>]
</p>

<?php echo $this->form; ?>