<?php
/**
 * list view script
 *
 * This view script is the list page for all users
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php foreach ($this->items as $user) : ?>

    <?php var_dump($user); ?>

<?php endforeach; ?>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>