<?php
/**
 * View script for logging out of the application
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @since       File available since release 1.0.0
 */
?>
<div class="article">
    <h2>Logout</h2>
    <p>
    You have been logged out of the application
    </p>
    <?php echo $this->htmlAnchor('Login', array(
        'module'    => 'default',
        'controller'=> 'users',
        'action'    => 'login',
        )); ?>
</div>

