<?php
/**
 * all view script
 *
 * This view script is for viewing all of the leaderboards for an event
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>
<?php
    // store request params for use later
    $params = $this->request()->getParams();

    $eventId = $params['id'];
    if (array_key_exists('event_id', $params)) :
        $eventId = $params['event_id'];
    endif;
?>

<div class="row">
    <div class="twelve columns">
        <?php foreach ($this->leaderboards as $leaderboard) : ?>
            <h2>
                <?php $title = ucwords($leaderboard->gender) . ' ' . $leaderboard->name; ?>
            </h2>

            <?php echo $this->htmlAnchor($title, array_merge($params, array(
                'controller'=> 'leaderboards',
                'action'    => 'view',
                'scale_id'  => $leaderboard->scale_id,
                'gender'    => $leaderboard->gender,
                'event_id'  => $eventId,
            ))); ?>
        <?php endforeach; ?>

    </div>
</div>