<?php
/**
 * Create view script
 *
 * This view script displays a form for creating
 *
 * @category    RxCompetition
 * @package     package
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<table>
<?php echo $this->leaderboardHeaders($this->items[0]); ?>
<?php foreach ($this->items as $index => $athlete) : ?>

    <?php echo $this->leaderboardItem($athlete, $index + 1); ?>

<?php endforeach; ?>

</table>