<?php
/**
 * view view script
 *
 * This view script is for viewing a single competition's leaderboards
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<table>
<?php echo $this->leaderboardHeaders($this->items[0]); ?>
<?php foreach ($this->items as $index => $athlete) : ?>

    <?php echo $this->leaderboardItem($athlete, $index + 1); ?>

<?php endforeach; ?>

</table>