<?php
/**
 * list view script
 *
 * This view script is the list page for all scores
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php foreach ($this->items as $event) : ?>

    <?php echo $this->scoreListItem($event); ?>

<?php endforeach; ?>