<?php
/**
 * view view script
 *
 * This view script is for viewing a single competition's leaderboards
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
));
?>

<table class="data-table leaderboards-table">
<?php
// render the leaderboard headers
echo $this->leaderboardHeaders(@$this->items[0]);

// set some variables to default values
$rank = 1;
$points = 0;

// iterate through each athlete's competition results
foreach ($this->items as $index => $athlete) :
    // update the points and rank values for the next item
    if ($athlete['points'] != $points) :
        $rank = $index + 1;
    endif;

    // render the leaderboard item
    echo $this->leaderboardItem($athlete, $rank);

    $points = $athlete['points'];

endforeach;

?>

</table>