<?php
/**
 * view view script
 *
 * This view script is for viewing a single competition's leaderboards
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
    $title = ucwords($this->request()->getParam('gender'))
        . ' - '
        . $this->scale->name;
?>
<h2><?php echo $title; ?></h2>
<?php

// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
));

echo $this->leaderboard()->table($this->items, $this->user);
?>
