<?php
/**
 * Create view script
 *
 * This view script displays a form for creating
 *
 * @category    RxComps
 * @package     package
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
// render a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
));

// render the creation form
echo $this->form;

?>