<?php
/**
 * list view script
 *
 * This view script is the list page for all scores
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
$eventId = $this->request()->getParam('event_id');

// echo the appropriate link to create a new score
echo $this->model(new App_Model_Score)->create($this->user, 'Add Score', array(
    'event_id'  => $eventId,
));

// iterate through the scores, rendering information
foreach ($this->items as $score) :

    echo $this->score($score)->item($this->user, array(
        'event_id'  => $eventId,
    ));

endforeach;

// output any pagination control necessary
// echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');

?>
