<?php
/**
 * view view script
 *
 * This view script is for viewing a single score record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php
// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink(
        $this->model->getParent('Athlete'),
        $this->request()->getParams()
    ),
    $this->model(new App_Model_Score)->create($this->user, 'Add Score', array(
        'event_id'  => $this->event()->id(),
    )),
));

echo $this->scoreItem($this->model->row, $this->user, array(
    'event_id'  => $this->event()->id(),
));

?>
