<?php
/**
 * view view script
 *
 * This view script is for viewing a single score record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php echo $this->htmlAnchor('Create New Score', array(
    'action'    => 'create',
)); ?>

<?php echo $this->scoreItem($this->model->row); ?>
