<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php
    $params = array();
    if (isset($this->additionalParams)) :
        $params = $this->additionalParams;
    endif;
?>

<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <?php echo $this->htmlAnchor('&lt; Previous', array_merge($params, array(
        'page'    => $this->previous,
    ))); ?>
    |
<?php else: ?>
    <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>

    <?php echo $this->htmlAnchor($page, array_merge($params, array(
        'page'    => $page,
    ))); ?>
    |
    <?php else: ?>
        <?php echo $page; ?> |
    <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>

    <?php echo $this->htmlAnchor('Next &gt;', array_merge($params, array(
        'page'    => $this->next,
    ))); ?>
<?php else: ?>
    <span class="disabled">Next &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>