<?php
/**
 * registration success email view script
 *
 * This view script should display any relevant information for someone who
 * has just successfully
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Emails
 * @copyright   Copyright (c) 2013 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<h1>You've Registered!</h1>

<p><?php echo $this->escape($this->athlete->getValue('name')); ?>,</p>

<p>Thank you for registering for the <?php echo $this->escape($this->event->getValue('name')); ?> event. Please
    take the opportunity to review your registration information below. </p>

<p>If you find anything incorrect about this information, Please send us an email so we can correct it

<a href="mailto:lee@baconbeatdown.com">lee@baconbeatdown.com</a>
</p>

<table width="100%">
    <tr>
        <td><strong>e-mail</strong></td>
        <td><?php echo $this->escape($this->user->getValue('email')); ?></td>
    </tr>
    <tr>
        <td><strong>Name</strong></td>
        <td><?php echo $this->escape($this->athlete->getValue('name')); ?></td>
    </tr>
    <tr>
        <td><strong>Event</strong></td>
        <td><?php echo $this->escape($this->event->getValue('name')); ?></td>
    </tr>
    <tr>
        <td><strong>Division</strong></td>
        <td><?php echo $this->escape($this->athlete->findParentRow('App_Model_DbTable_Scale')->name); ?></td>
    </tr>
    <tr>
        <td><strong>Gender</strong></td>
        <td><?php echo $this->escape($this->athlete->getValue('gender')); ?></td>
    </tr>
    <tr>
        <td><strong>Gym</strong></td>
        <td><?php echo $this->escape($this->athlete->getValue('gym')); ?></td>
    </tr>
</table>

<p>Best,</p>
<?php echo @$this->options['salutation']; ?>
