<?php
/**
 * registration success email view script
 *
 * This view script should display any relevant information for someone who
 * has just successfully
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Emails
 * @copyright   Copyright (c) 2013 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<h1>You've Registered!</h1>

<p><?php echo $this->escape($this->athlete->getValue('name')); ?>,</p>

<p>Thank you for registering for the <?php echo $this->escape($this->event->getValue('name')); ?> event. Please
    take the opportunity to review your registration information below. </p>

<p>If you find anything incorrect about this information, you can login and edit
    it <?php echo $this->htmlAnchor('here', array(
        'controller' => 'registrations',
        'action'    => 'edit',
        'id'        => $this->model->id,
        'event_id'  => $this->event->id,
    )); ?>
</p>

<table width="100%">
    <tr>
        <td>e-mail</td>
        <td><?php echo $this->escape($this->user->getValue('email')); ?></td>
    </tr>
    <tr>
        <td>Name</td>
        <td><?php echo $this->escape($this->athlete->getValue('name')); ?></td>
    </tr>
    <tr>
        <td>Event</td>
        <td><?php echo $this->escape($this->event->getValue('name')); ?></td>
    </tr>
    <tr>
        <td>Division</td>
        <td><?php echo $this->escape($this->athlete->getValue('scale_id')); ?></td>
    </tr>
    <tr>
        <td>Gender</td>
        <td><?php echo $this->escape($this->athlete->getValue('gender')); ?></td>
    </tr>
    <tr>
        <td>Gym</td>
        <td><?php echo $this->escape($this->athlete->getValue('gym')); ?></td>
    </tr>
</table>

<p>Best,</p>
<?php echo @$this->options['salutation']; ?>
