<?php
/**
 * build athlete index view script
 *
 * The view script for building the lucene index of athletes
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2013 RxComps, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>
<?php
// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink(new App_Model_Event, $this->request()->getParams()),
));
?>
<h2><?php echo $this->translate('Build Athlete Search Index'); ?>

<?php echo $this->form; ?>