<?php
/**
 * build athlete index view script
 *
 * The view script for building the lucene index of athletes
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2013 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<h2><?php echo $this->translate('Build Athlete Search Index'); ?>

<?php echo $this->form; ?>