<?php
/**
 * flush page cache view script
 *
 * The view script for editing event options
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2013 RxComps, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<?php

// store request params for use later
$params = $this->request()->getParams();

$eventId = $params['event_id'];

// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink(new App_Model_Event, $this->request()->getParams()),
));
?>

<h2><?php echo $this->translate('Page Cache Flushed'); ?></h2>