<?php
/**
 * index view script
 *
 * The default view script for the admin section
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2013 RxComps, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<?php
// render a link back to the main event
echo $this->actionList(array(
    // link to clear the cache
    '<div class="medium info btn icon-left entypo icon-ccw">' .
    $this->htmlAnchor($this->translate('Clear Page Cache'), array(
        'controller'    => 'admin',
        'action'        => 'flush-cache',
    ))
    . '</div>',

    // link to build the athlete index
    '<div class="medium info btn icon-left entypo icon-users">' .
    $this->htmlAnchor($this->translate('Build Athlete Index'), array(
        'controller'    => 'admin',
        'action'        => 'build-athlete-index',
    ))
    . '</div>',

));
