<?php
/**
 * index view script
 *
 * The default view script for the admin section
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2013 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 2.0.0
 * @since       File available since release 2.0.0
 */
?>

<?php
// render a link back to the main event
echo $this->actionList(array(
    // link to clear the cache
    $this->htmlAnchor($this->translate('Clear Page Cache'), array(
        'controller'    => 'admin',
        'action'        => 'flush-cache',
    )),

    // link to build the athlete index
    $this->htmlAnchor($this->translate('Build Athlete Index'), array(
        'controller'    => 'admin',
        'action'        => 'build-athlete-index',
    )),

));
