<?php
/**
 * Default layout view script
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @since       File available since release 1.0.0
 */
?>
<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <title>Rx Competition</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width" />

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="/css/normalize.css" />
        <link rel="stylesheet" href="/css/screen.css" />
        <link rel="stylesheet" href="/css/style.css" />

        <meta name="keywords" content="" />
        <meta name="description" content="" />

        <link rel="stylesheet" type="text/css" media="screen and (max-device-width: 480px)" href="/css/mobile.css" />
        <!--[if IE]>
            <link rel="stylesheet" type="text/css" href="/css/ie.css" />
        <![endif]-->
        <!--[if IE8]>
            <link rel="stylesheet" type="text/css" href="/css/ie8.css" />
        <![endif]-->
        <script src="/js/vendor/modernizr-2.6.2.min.js"></script>

    </head>
    <body class="">
        <div class="header">
            <h1 class="container"><a href="/">Rx Competition</a></h1>
        </div>
        <div class="nav">
            <?php echo $this->navigation()->menu()->setUlClass('container')->menu(); ?>
        </div>
        <div class="content">
            <div class="container">
            <?php echo $this->flashMessenger($this->flashMessenger); ?>
            <div class="page-content">
                <?php echo $this->layout()->content; ?>
            </div>
            </div>
        </div>
        <div class="footer">
            <div class="container">
            </div>
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.8.2.min.js"><\/script>')</script>
        <script src="/js/plugins.js"></script>
        <script src="/js/main.js"></script>
    </body>
</html>
