<?php
/**
 * Default layout view script
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @since       File available since release 1.0.0
 */
?>
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en" itemscope itemtype="http://schema.org/Product"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en" itemscope itemtype="http://schema.org/Product"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <!-- Use the .htaccess and remove these lines to avoid edge case issues.
    More info: h5bp.com/b/378 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><?php echo $this->title; ?></title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="humans.txt">

    <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />

    <!--Facebook Metadata /-->
    <meta property="fb:page_id" content="" />
    <meta property="og:image" content="" />
    <meta property="og:description" content=""/>
    <meta property="og:title" content=""/>

    <!--Google+ Metadata /-->
    <meta itemprop="name" content="">
    <meta itemprop="description" content="">
    <meta itemprop="image" content="">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

    <!-- CSS: implied media=all -->
    <!-- CSS concatenated and minified via ant build script-->
    <!-- <link rel="stylesheet" href="css/minified.css"> -->

    <!-- CSS imports non-minified for staging, minify before moving to production-->
    <link rel="stylesheet" href="/css/gumby.css">
    <link href="/css/print.css" media="print" rel="stylesheet" type="text/css" />
    <!--[if lt IE 8]>
      <link href="/src/pub/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
    <![endif]-->
    <!-- end CSS-->

    <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

    <!-- All JavaScript at the bottom, except for Modernizr / Respond.
    Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
    For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
    <script src="/js/libs/modernizr-2.6.2.min.js"></script>
</head>

<body>
    <div class="header">
        <div class="container row">

            <div id="navigation" class="navbar" gumby-fixed="top">
            <h2 class="logo"><a href="/">Rx Comps</a></h2>
                <a class="toggle" gumby-trigger="#navigation > ul" href="#">
                    <i class="icon-menu"></i>
                </a>

                <?php echo $this->navigation()
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->render(); ?>
            </div>
        </div>
    </div>

    <div class="container row page-content">
        <?php echo $this->flashMessenger($this->flashMessenger); ?>
        <div class="breadcrumbs">
            <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setMaxDepth(5)->render(); ?>
        </div>
        <?php echo $this->layout()->content; ?>
    </div>

    <div class="footer">
        <div class="container row">
        <p>&copy; RxComps. All rights reserved. RxComps and RxComps.com are trademarks
        and/or service marks of RxComps.com, Inc. Use of this website constitutes
        acceptance of the Subscriber Agreement and Privacy Policy. All programs,
        processes, and source code contained on this website, RxComps.com
        are protected by license and are patent pending. Other information, logos,
        company names, website names, and/or trademarks that appear on this
        website are the copyrighted property of their respective companies.
        this site and it's content may not be copied, modified, reproduced, republished,
        transmitted, or distributed without the authorization of RxComps.com
        </p>
        <p>
        For more information, please visit the RxComps.com
        <?php echo $this->htmlAnchor('Terms of Use', array(
            'module' => 'default',
            'controller' => 'index',
            'action'    => 'terms-of-use',
        )); ?>
        </p>
        </div>
    </div>

    <!-- Grab Google CDN's jQuery, fall back to local if offline -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.10.1.min.js"><\/script>')</script>

    <?php // render all of the javascript
        echo implode(PHP_EOL, array(
            $this->headScript(),
            $this->inlineScript(),
        )) . PHP_EOL;
    ?>
</body>
</html>
