<?php
/**
 * Default layout view script
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @since       File available since release 1.0.0
 */
?>
<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>

        <title>Rx Competition</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <meta name="keywords" content="" />
        <meta name="description" content="" />

        <link rel="stylesheet" type="text/css" media="screen and (max-device-width: 480px)" href="/css/mobile.css" />
        <!--[if IE]>
            <link rel="stylesheet" type="text/css" href="/css/ie.css" />
        <![endif]-->
        <!--[if IE8]>
            <link rel="stylesheet" type="text/css" href="/css/ie8.css" />
        <![endif]-->

    </head>
    <body class="">
        <div class="header">
            <h1 class="container"><a href="/">Rx Competition</a></h1>
        </div>
        <div class="nav">
            <div class="container">
            </div>
        </div>
        <div class="content">
            <div class="container">
            <div class="page-content">
                <?php echo $this->layout()->content; ?>
            </div>
            </div>
        </div>
        <div class="footer">
            <div class="container">
            </div>
        </div>

        <script type="text/javascript" src="/js/1.6.3.jquery-min.js"></script>
        <script type="text/javascript" src="/js/modernizr-1.7.min.js"></script>
        <script type="text/javascript" src="/js/jquery.validate.pack.js"></script>
    </body>
</html>
