<?php
/**
 * Create view script
 *
 * This view script displays a form for creating
 *
 * @category    RxCompetition
 * @package     package
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>
<?php echo $this->htmlList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
), false, array(
    'class' => 'subnav',
), false); ?>

<?php echo $this->form; ?>