<?php
/**
 * Leaderboards view script
 *
 * This view script displays the leaderboards for a specific competition
 *
 * @category    RxCompetition
 * @package     package
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<table class="data-table leaderboards-table">
<thead>
    <th class="athlete-name"><p class="rotate">Athlete / Team</p></th>
    <th class=""><p class="rotate">Score</p></th>
</thead>
<tbody>

<?php foreach ($this->items as $index => $athlete) : ?>

    <?php $athlete['competitions'] = array(
        $athlete['competition_id'] => array(
            'score'     => $athlete['score'],
            'rank'      => $athlete['rank'],
            'points'    => $athlete['points'],
        ),
    ); ?>

    <?php echo $this->leaderboardItem($athlete, $athlete['rank']); ?>

<?php endforeach; ?>
</tbody>

</table>

