<?php
/**
 * Leaderboards view script
 *
 * This view script displays the leaderboards for a specific competition
 *
 * @category    RxCompetition
 * @package     package
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition, Inc (http://www.rxcompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<h2>Leaderboards for <?php echo ucwords($this->model->getValue('name')); ?></h2>

<?php
    // setup the actors for the view
    $athleteTable       = new App_Model_DbTable_Athlete;
    $competitionTable   = new App_Model_DbTable_Competition;
?>
<table>
    <tr>
        <th>Result</th>
        <th>Score</th>
        <th>Athlete</th>
    </tr>
<?php foreach ($this->leaderboards as $entry) : ?>
<?php
    $athlete        = $athleteTable->fetchRow(sprintf('id = %d', $entry['athlete_id']));
    $competition    = $competitionTable->fetchRow(sprintf('id = %d', $entry['competition_id']));
?>
    <tr>
        <td><?php echo $entry['score']; ?></td>
        <td><?php echo $entry['points']; ?></td>
        <td><?php echo $athlete->name; ?></td>
    </tr>
<?php endforeach; ?>
</table>
