<?php
/**
 * list view script
 *
 * This view script is the list page for all competitions
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php if ($this->auth()->hasIdentity()) :?>
<?php echo $this->htmlList(array(
    $this->htmlAnchor('Add Competition', array(
        'controller'    => 'competitions',
        'action'    => 'create',
    ))
), false, array(
    'class' => 'subnav',
), false); ?>
<?php endif; ?>

<?php foreach ($this->items as $competition) : ?>

    <?php echo $this->competitionItem($competition); ?>

<?php endforeach; ?>
