<?php
/**
 * view view script
 *
 * This view script is for viewing a single competition record
 *
 * @category    RxCompetition
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxCompetition.com, Inc (http://www.RxCompetition.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php echo $this->htmlList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
    $this->htmlAnchor('Enter Scores', array(
        'controller'    => 'scores',
        'action'        => 'create',
        'event_id'      => $this->model->getParent('Event')->id,
        'competition_id'=> $this->model->id,
    ))
), false, array(
    'class' => 'subnav',
), false); ?>

<h2><?php echo $this->model->getValue('name'); ?></h2>
<p><?php echo strtr($this->model->getValue('description'), array(
    PHP_EOL => '</p><p>',
)); ?></p>
<p></p>

<h3>Leaderboards</h3>
<?php
    $event = $this->model->getParent('Event');
?>
<?php echo $this->action('leaderboards', 'competitions', 'default', array_merge(
    $this->request()->getParams(),
    array('event_id' => $event->id,)
));?>