<?php
/**
 * view view script
 *
 * This view script is for viewing a single competition record
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

<?php

$eventId = $this->request()->getParam('event_id');

// echo a link back to the main event
echo $this->actionList(array(
    $this->backToEventLink($this->model, $this->request()->getParams()),
    $this->model(new App_Model_Score)->create($this->user, 'Add Score', array(
        'event_id'  => $eventId,
        'competition_id'=> $this->model->id,
    )),
));

echo $this->competition($this->model->row)->item($this->user, array(
    'event_id'  => $eventId,
));

?>

<h2><?php echo $this->model->getValue('name'); ?></h2>
<p><?php echo strtr($this->model->getValue('description'), array(
    PHP_EOL => '</p><p>',
)); ?></p>
<p></p>
