<?php
/**
 * Denied view script
 *
 * This view script displays a message to a user that the resource they are
 * trying to access was denied to them
 *
 * @category    RxComps
 * @package     App
 * @subpackage  View_Scripts
 * @copyright   Copyright (c) 2012 RxComps.com, Inc (http://www.RxComps.com)
 * @license     All Rights Reserved
 * @version     Release: 1.0.0
 * @since       File available since release 1.0.0
 */
?>

denied